"""empty message

Revision ID: aed290c463bf
Revises: f92c9febf5a9
Create Date: 2023-05-10 18:45:40.134206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed290c463bf'
down_revision = 'f92c9febf5a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('population')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('population', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
